[package]
name = "challenge3"
version = "0.1.0"
edition = "2018"


[dependencies]
riscv-rt = "0.8.0"
panic-halt = "0.2.0"
embedded-graphics = "0.7.1"
longan-nano = { version = "0.3.0", features = ["lcd"] }
riscv = "0.7.0"